[project]
name = "data-accelerator"
version = "0.1.0"
description = "Basic template for pyspark project using mise and UV"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyspark[connect]>=3.5.5",
    "sqlfluff>=3.3.1",
]

[dependency-groups]
dev = [
    "bandit>=1.8.3",
    "pre-commit>=4.2.0",
    "pyright>=1.1.398",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["src"]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
